name = "gemini-cli-proxy"
main = "build/worker.mjs"
compatibility_date = "2022-05-13"
account_id = "02c07a2514d9a25f58c78a180bb8c6f3"
compatibility_flags = [
    "streams_enable_constructors"
]
kv_namespaces = [
  { binding = "GEMINI_CLI_KV", id = "" }
]

[build]
command = "just build-worker"
